"""
    Utililty files 

    Authors:
     Zihan Liu <leoliu00529@gmail.com>
"""

class InstanceFeatures():
    def __init__(self,
                 tokens,
                 token_ids,
                 token_mask,
                 labels,
                 label_ids,
                 token_to_orig_map,
                 sentence,
                 we_indices):
        """
        Attributes of this class:
            self.tokens: a list of tokens (str) generated by BertTokenizer.
            self.token_ids: a list of the IDs of the self.tokens. Please note 
                that len(token_ids) = len(tokens) + 2 due to the insertions special
                tokens of [CLS] and [SEP].
            self.token_mask: a by-product of BertTokenizer for as the 
                mask input to Bert model.
            self.labels: one of the five labels {B-A, B-S, I-A, I-S, O}
            self.label_ids: one ID for each label (1 to 5)
            self.token_to_orig_map: the mapping from positions of token ids to 
                the position of the original word. E.g., if [A, B, C] is tokenized
                to [[CLS], A, B1, B2, B3, C, [SEP]], the mapping is 
                {1:0, 2:1, 3:1, 4:1, 5:2}.
            self.sentence: the tokenized and then `convert_tokens_to_sentence()`-ed
                sentence.
            self.we_indices: Set to None for now.
        """
        self.tokens     = tokens
        self.token_ids  = token_ids
        self.token_mask = token_mask
        self.labels     = labels
        self.label_ids  = label_ids
        self.token2orig = token_to_orig_map
        self.sentence   = sentence
        self.we_indices = we_indices